services:
  json-server:
    image: json-server-dev-image
    build:
      context: .
      dockerfile: ./backend/db.dev.Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001

  backend:
    image: mood-tracker-backend-image
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
    environment:
      - DB_URL=http://json-server:3001/entries
    depends_on:
      - json-server

  frontend:
    image: mood-tracker-frontend-image
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    ports:
      - 80:80
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
