services:
  json-server:
    image: json-server-dev-image
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001

  backend:
    image: mood-tracker-backend-dev-image
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - DB_URL=http://json-server:3001/entries
    depends_on:
      - json-server

  frontend:
    image: mood-tracker-frontend-dev-image
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:3000
    depends_on:
      - backend
