### backend = localhost:3000
### db = localhost:3001

### backend
GET http://localhost:3000/api/hello

### 
GET http://localhost:3000/api/entries

### backend
POST http://localhost:3000/api/entries
Content-Type: application/json

{
  "mood": "joy",
  "message": "hello"
}
