name: Deploy to DigitalOcean

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to DigitalOcean
        run: |
          ssh nodeapp@159.223.191.151 /bin/bash << EOF
          cd ~/full-stack-mood-tracker
          git pull origin main
          pnpm install
          pnpm build
          pm2 restart ./backend/dist/backend/index.js
          EOF
