name: Full Test Suite

on: workflow_dispatch

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: install dependencies
        run: pnpm install
      - name: run linter
        run: pnpm run lint
      - name: build
        run: pnpm run build
      - name: unit tests
        run: pnpm run test:unit
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: run playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
